version: '3'

services:
  currency-limit-manager:
    image: currency-limit-manager:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - spring.application.name=CurrencyLimitManager
      - spring.datasource.url=jdbc:postgresql://db:5432/currencylimitmanager_db
      - spring.datasource.username=postgres
      - spring.datasource.password=admin
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.flyway.validate-on-migrate=true
      - spring.flyway.baseline-on-migrate=true
      - spring.flyway.locations=classpath:db/migration
      - logging.level.root=info
      - logging.file.name=logs/application.log
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: currencylimitmanager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
